apiVersion: netbox.upbound.io/v1beta1
kind: ProviderConfigUsage
metadata: {}
providerConfigRef:
  name: string
  policy:
    resolution: string
    resolve: string
resourceRef:
  apiVersion: netbox.upbound.io/v1beta1
  kind: ProviderConfigUsage
  name: string
  uid: string
